language: c
os: windows

# Default job task: run tests as defined in the $OPT environment variable.
# Jobs can redefine the 'script' stage in the matrix below.

# All the job definitions in the matrix.
matrix:
  include:

    - name: "Windows/x86 Build"
      script: tools/build.py

    - name: "Windows/x86 Jerry-tests"
      script: ./test1.bat

    - name: "Windows/x86 Jerry testsuite"
      script: ./test2.bat

    - name: "Windows/x86 Build Tests"
      script: ./test3.bat

    - name: "Windows/x86 Conformance Tests"
      script: ./test4.bat

    - name: "Windows/x86 Unit Tests"
      script: ./test5.bat

  fast_finish: true
